#DATA LOADER CONFIG
YEAR = 2023
GRAND_PRIX = "Hungary"
SESSION_TYPE = "Q"
DRIVERS = ["VER", "HAM"]
CACHE_DIR = "cache"
N_POINTS = 1000

#ENVIRONMENT CONFIG
SPEED            = 0.15
STEER_ANGLE      = 0.12
MAX_STEPS        = 2000
TRACK_HALF_W     = 1.2
DIST_PENALTY_K   = 2.0
HEADING_BONUS_K  = 0.4
OFF_TRACK_REWARD = -10.0
STEP_SURVIVAL    = 0.05

#MODEL CONFIG
STATE_LAYER = 7
ACTION_LAYER = 3
HIDDEN_LAYER = 64